# Site settings
title: LGD.Hua-个人博客
author: LGD.HuaOPER
email:  1094360174@qq.com
description: > # this means to ignore newlines until "baseurl:"
  LGD.HuaOPER, LGD.HuaFEEng——The goal is to be a full stack engineer.

# Site URL NOTE: if your site is base on subdir /blog you should change base to "/blog"
domain: "https://lgdhuaoper.github.io" # the domain URL for your site
base: ""  # the relative path that different with domain so you can test locally

# Source PATH
postfile: "/db/Postfile" # the Database
sitefile: "/db/Sitefile" # the Database
resource_path: "/resource"
js_path: "/resource/js"
css_path: "/resource/css"
img_path: "/resource/img"

# pagination
page_size: 3

# comment settings

# subPATH
jquery_subpath: "lib/jquery.min.js"
bootstrap_js_subpath: "lib/bootstrap.min.js"
moment_subpath: "lib/moment.min.js"
baiduTemplate_subpath: "lib/baiduTemplate.js"
bootstrap_css_subpath: "lib/bootstrap.min.css"

# key
google_analytics_id: ""
baidu_tongji_id: ""

# Build Settings
excerpt_separator: "\n\n" # you can specify your own separator here, default is "\n\n" String
permalink: /:year/:month/:day/:title.html
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true # a newline in markdown text would be changed to <br>
gems:
  - jemoji    # enable the github emoji
version: 1.1.0

# Following is got in Github Help With Configuring Jekyll

# Github Page Default Settings which you can override:
# kramdown:
#   input: GFM
#   hard_wrap: false
# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate

# Github Page override the following settings which you cannot change:
# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#  noscript: false
# kramdown:
#  math_engine: mathjax
